#!/usr/bin/env bash
set -eux

docker build -t openresty-bundle-deb .
CONTAINER=$(docker create openresty-bundle-deb)
if [ ! -d ./artifacts ]; then
    mkdir ./artifacts
fi
docker cp $CONTAINER:/build/artifacts/ ./
docker rm $CONTAINER
