#!/usr/bin/env bash
set -eux

docker build -t openresty-bundle-deb-xenial .
CONTAINER=$(docker create openresty-bundle-deb-xenial)
if [ ! -d ./artifacts ]; then
    mkdir ./artifacts
fi
docker cp $CONTAINER:/build/artifacts/ ./
docker rm $CONTAINER
